package pe.interbank.captaciones;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(74a0f53836ca7f14f8e853d763d67d0f)
 */
@org.kie.api.definition.type.Label(value = "Cuenta")
public class Cuenta  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "derechoCuenta")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Boolean derechoCuenta;
    
    @org.kie.api.definition.type.Label(value = "monto")
    @org.kie.api.definition.type.Position(value = 0)
    private int monto;
    
    @org.kie.api.definition.type.Label(value = "producto")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Boolean producto;

    public Cuenta() {
    }

    public Cuenta(int monto, java.lang.Boolean producto, java.lang.Boolean derechoCuenta) {
        this.monto = monto;
        this.producto = producto;
        this.derechoCuenta = derechoCuenta;
    }


    
    public java.lang.Boolean getDerechoCuenta() {
        return this.derechoCuenta;
    }

    public void setDerechoCuenta(java.lang.Boolean derechoCuenta) {
        this.derechoCuenta = derechoCuenta;
    }
    
    public int getMonto() {
        return this.monto;
    }

    public void setMonto(int monto) {
        this.monto = monto;
    }
    
    public java.lang.Boolean getProducto() {
        return this.producto;
    }

    public void setProducto(java.lang.Boolean producto) {
        this.producto = producto;
    }
}