import pe.interbank.captaciones.Captacion;
	
	//from row number: 1
	rule "Row 1 puntaje"
	ruleflow-group "captaciones"
       dialect "mvel"
       when
	        f1 : Captacion( edad <= 25 , puntaje >= 1000 )
      then
	        f1.setViaRapida( true );
	end
	
	//from row number: 2
	rule "Row 2 puntaje"
       ruleflow-group "captaciones"
       dialect "mvel"
       when
	        f1 : Captacion( edad <= 25 , puntaje >= 99999999 )
      then
       	        f1.setViaRapida( false );
      end